# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            Gone For A Run
description:      'Where else would I have gone?'
url:              https://gonefora.run
baseurl:          ""
logo:             /assets/favicon.png
author:           'Colin Seymour'
lang:             en-GB
theme:            minima-dude

# Defaults for the entire site
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""

twitter:
  username:       lildude
strava:
  id:             1295848
parkrun:
  id:             73185
powerof10:
  id:             246985

microblog:
  username:       lildude
  site:           dev

social:
  name:           Colin Seymour
  links:
    - https://twitter.com/lildude
    - https://www.instagram.com/lildoodlil/
    - https://www.strava.com/athletes/1295848

# Theme settings
minima_dude:
  date_format: "%-d %b %Y"
  whackwhack: true    # Splits site title into spaces, adds // to the beginning and colours the words so the first half are white and the second half are red
  show_author: false

# Custom vars
google_site_verification:   X0GErJ8t4_IcMSb7Xy8JYdK8qlk_QoqgsxI3r94fe4A

sass:
  sass_dir:       _scss
  style:          compressed

compress_html:
  clippings:      all
  comments:       ["<!-- ", " -->"]
  #endings:        all # Commented out in favour of selecting all _except_ p as this breaks formatting
  endings:        [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  ignore:
    envs:         [test, local, development]
  profile:        false
  startings:      [html, body]

# Configure kramdown
kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-json-feed
  - jekyll-feed

# Configure jekyll-feed
feed:
  path: atom.xml
  use_excerpts: false

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README.md, vendor, sitespeed-result, script]
# Don't attempt to process these - ie leave as-is
keep_files: [assets, img]
