# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            Barefoot Runner
tagline:          'From Shoes to Nothing'
description:      "I ran. I ran fast. I ran lots. I stopped, got fat and now I'm back, but this time barefoot and almost barefoot with new goals, dreams and aspirations."
url:              https://barefootrunner.co.uk
baseurl:          ""
twitter:
  username:       lildude
logo:             assets/profile.png
author:           'Colin Seymour'

social:
  name:           Colin Seymour
  links:          ["https://twitter.com/lildude", "https://www.instagram.com/lildoodlil/"]

# Custom vars
google_site_verification:   X0GErJ8t4_IcMSb7Xy8JYdK8qlk_QoqgsxI3r94fe4A

sass:
  sass_dir:       _scss
  style:          compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [test, local]
  profile: false
  startings: [html, body]

# Configure RedCarpet
redcarpet:
  extensions:       [tables, autolink, strikethrough, footnotes, superscript]

# Configure kramdown
kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
gems:
  - jekyll-sitemap
  #- jekyll/twemoji
  #- jemoji
  - jekyll-paginate
  - jekyll-emoji
  #- jekyll-seo-tag

# jekyll-emoji config - note, it's use of "Emoji" module name clashes with other gems.
emoji:
  format: emojione-svg-embed # default html
  ascii: false # default false
  shortname: true # default true
  src: "/Users/lildude/Sites/static/emojione/svg" # defaults to https://cdn.jsdelivr.net/emojione/assets/#{ext}
  #src: "https://twemoji.maxcdn.com/svg/" # Twmoji
  #src: "https://cdn.jsdelivr.net/emojione/assets/svg"

#jekyll-twemoji:
#  image_type: "svg"

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README-hyde.md, README.md]
