# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            Gone For A Run
description:      'Where else would I have gone?'
url:              https://gonefora.run
baseurl:          ""
logo:             /assets/favicon.png
author:           'lildude'
lang:             en-GB
theme:            minima-dude

dns_prefetch:
  - images.weserv.nl
  - d33wubrfki0l68.cloudfront.net

# Defaults for the entire site - this ensures my notes and photos which use implied titles don't get a title in the feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""

twitter:
  username:       lildude
strava:
  id:             1295848
parkrun:
  id:             73185
powerof10:
  id:             246985

microblog:
  username:       lildude
  site:           /run     # Needs the slash cos I'm lazy in my theme.
webmentions:      gonefora.run

social:
  name:           Colin Seymour
  links:
    - https://twitter.com/lildude
    - https://www.instagram.com/lildoodlil/
    - https://www.strava.com/athletes/1295848

# Theme settings
minima_dude:
  date_format: "%-d %b %Y"
  whackwhack: true    # Splits site title into spaces, adds // to the beginning and colours the words so the first half are white and the second half are red
  show_author: false

# Custom vars
google_site_verification:   X0GErJ8t4_IcMSb7Xy8JYdK8qlk_QoqgsxI3r94fe4A

sass:
  sass_dir:       _scss
  style:          compressed

# Configure kramdown
kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

# Plugins
plugins:
  - jekyll-feed
  #- jekyll-image-cache
  - jekyll-include-cache
  #- jekyll-loading-lazy
  - jekyll_picture_tag
  - jekyll-seo-tag
  - jekyll-sitemap

# Configure jekyll-feed
feed:
  path: atom.xml
  use_excerpts: false

picture:
  #source: "img"
  output: "g"
  relative_url: false
  ignore_baseurl: true
  fast_build: development

# Don't copy these files to the generated site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - LICENSE
  - Rakefile
  - README.md
  - vendor
  - sitespeed-result
  - script
  - .jekyll-cache
  - package.json
  - package-lock.json
  - postcss.config.js
  - tmp
# Don't attempt to process these - ie leave as-is
keep_files:
  - assets
  - img
