# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        :title

# Setup
title:            Barefoot Runner
tagline:          'From Shoes to Nothing'
description:      "I ran. I ran fast. I ran lots. I stopped, got fat and now I'm back, but this time barefoot and almost barefoot with new goals, dreams and aspirations."
url:              https://barefootrunner.co.uk
baseurl:          /

author:
  name:           'Colin Seymour'
  url:            https://twitter.com/lildude
  twitter:        '@lildude'

paginate:         10

# Custom vars
version:          0.0.1
google-site-verification: X0GErJ8t4_IcMSb7Xy8JYdK8qlk_QoqgsxI3r94fe4A
debug:            false

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir:       _scss
  style:          compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []

# Configure RedCarpet
redcarpet:
  extensions:       [tables, autolink, strikethrough, footnotes, superscript]
  
# Plugins
gems:
  - jemoji
  - jekyll-sitemap

# Don't copy these files to the generated site
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE.md, Rakefile, README-hyde.md, README.md]
