# See https://www.netlify.com/docs/netlify-toml-reference/
[Settings]
ID = "f2149f79-c71c-480c-98d0-66e917ce60cf"

[build]
  publish = "_site/"
  command = "bundle exec jekyll build"

[context.production.environment]
  JEKYLL_ENV = "production"

# JEKYLL_ENV defaults to development so commenting out
#[context.branch-deploy.environment]
#  JEKYLL_ENV = "development"