media_folder: "img"
public_folder: "/img"
logo_url: https://gonefora.run/assets/favicon.png
display_url: https://gonefora.run
site_url: https://gonefora.run
publish_mode: editorial_workflow
backend:
  name: git-gateway #test-repo
  branch: main
collections:
  - name: "note"
    label: "Note"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    filter:
      field: "layout"
      value: "note"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "note"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", format: "LLL", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss ZZ"}
    - {label: "Body", name: "body", widget: "markdown", editor_components: [], buttons: [bold, italic, code, link, quote, bulleted-list, numbered-list]}
  - name: "photo"
    label: "Photo"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    filter:
      field: "layout"
      value: "photo"
    editor:
      preview: true
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "photo"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", format: "LLL", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss ZZ"}
    - {label: "Body", name: "body", widget: "markdown", minimal: true, buttons: [], editor_components: ["photo"], modes: ["rich_text"]}
  - name: "post"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    filter:
      field: "layout"
      value: "post"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", format: "LLL", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss ZZ"}
    - {label: "Tags", name: "tags", widget: "list", allow_add: true, collapsed: true}
    - {label: "Body", name: "body", widget: "markdown"}