name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install libvips
      run: sudo apt-get -y  install --no-install-recommends libvips libvips-tools

    - name: Cache HTMLProofer
      id: cache-htmlproofer
      uses: actions/cache@v2
      with:
        path: tmp/.htmlproofer
        key: ${{ runner.os }}-htmlproofer

    - name: Run tests
      run: script/cibuild