name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Install libvips
      run: sudo apt-get -y  install --no-install-recommends libvips libvips-tools
    - name: Run tests
      run: script/cibuild