name: Sync WP to Static

on:
  schedule:
    - cron:  '11 * * * 1'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Sync New Posts
        uses: lildude/sync-wp-to-static@master
        env:
          wordpress_token: ${{ secrets.WORDPRESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_template: script/template.erb
          posts_path: _posts
          imgs_path: img
          wordpress_endpoint: https://public-api.wordpress.com/wp/v2/sites/fundiworks.wordpress.com
          include_tagged: "run"
